# Generated by Django 3.2.22 on 2023-10-05 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_article_tags'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article',
            new_name='Articles',
        ),
    ]
